In [41]:
import torch

In [42]:
t1=torch.tensor([[1,2],[3,4]])
# t2=torch.tensor([[1,2],[3,4]], device='cuda:0')
t3=torch.tensor([[1,2],[3,4]], dtype=torch.float64)
print(t1)
# print(t2)
print(t3)

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [43]:
t4=torch.FloatTensor([[1,2],[3,4]])
t5=torch.LongTensor([[1,2],[3,4]])
t6=torch.ByteTensor([[1,2],[3,4]])
print(t4)
print(t5)
print(t6)


tensor([[1., 2.],
        [3., 4.]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)


In [44]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)
print(type(x))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [45]:
t=torch.from_numpy(x) # numpy array -> torch tensor로
print(t, type(t))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>


In [46]:
nx=t.numpy() # tensor -> numpy array로
print(nx)

[[1 2]
 [3 4]]


In [47]:
# 데이터 형 변환
ft=torch.FloatTensor([[1,2,3],[4,5,6]])
print(ft)
lt=ft.long() #LongTensor로 바꾸기
print(lt)
bt=lt.byte() #ByteTensor로 바꾸기
print(bt)
ft1=lt.float() #FloatTensor 바꾸기
print(ft1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.uint8)
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [48]:
x=torch.tensor([[[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]])
print(x)

tensor([[[[ 1,  2],
          [ 3,  4],
          [ 5,  6]],

         [[ 7,  8],
          [ 9, 10],
          [11, 12]]]])


In [49]:
print(x.size())
print(x.shape)
print(x.size(0))
print(x.size(1))
print(x.size(2))
print(x.shape[0])
print(x.shape[-1]) # 맨마지막 요소가 나온다
print(x.dim())
print(len(x.size()))

torch.Size([1, 2, 3, 2])
torch.Size([1, 2, 3, 2])
1
2
3
1
2
4
4


In [50]:
# 텐서끼리 연산
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[4,4]])
print(a)
print(b)

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 2.],
        [4., 4.]])


In [51]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a==b)
print(a!=b)
print(a**b)

tensor([[3., 4.],
        [7., 8.]])
tensor([[-1.,  0.],
        [-1.,  0.]])
tensor([[ 2.,  4.],
        [12., 16.]])
tensor([[0.5000, 1.0000],
        [0.7500, 1.0000]])
tensor([[False,  True],
        [False,  True]])
tensor([[ True, False],
        [ True, False]])
tensor([[  1.,   4.],
        [ 81., 256.]])


In [52]:
print(a)
print(a.mul(b))
print(a)
print(a.mul_(b))
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [12., 16.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [12., 16.]])
tensor([[ 2.,  4.],
        [12., 16.]])


In [53]:
x=a
print(x)
print(x.sum())
print(x.sum(dim=0)) # col별 sum
print(x.sum(dim=1)) # row별 sum
print(x.mean())
print(x.mean(dim=0)) # col별 mean
print(x.mean(dim=1)) # row별 mean

tensor([[ 2.,  4.],
        [12., 16.]])
tensor(34.)
tensor([14., 20.])
tensor([ 6., 28.])
tensor(8.5000)
tensor([ 7., 10.])
tensor([ 3., 14.])


In [54]:
# 텐서+스칼라(=일반숫자)
y=1
z=x+y
print(x.size())
print(z)
print(z.size())

torch.Size([2, 2])
tensor([[ 3.,  5.],
        [13., 17.]])
torch.Size([2, 2])


In [55]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([3,4])
print(y.size())
z=x+y
print(z)
print(z.size())

torch.Size([2])
tensor([[4., 6.],
        [6., 8.]])
torch.Size([2, 2])


In [56]:
x=torch.FloatTensor([[1,2]])
y=torch.FloatTensor([[3],[4]])
print(x.size())
print(y.size())
z=x+y
print(z)
print(z.size())

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])
torch.Size([2, 2])


In [57]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
x=torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
y=torch.FloatTensor([1,2,3,4,5,6,7,8,9,10,11,12])
print(x)
print(x.size())
print(y)
print(y.size())

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
torch.Size([3, 2, 2])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
torch.Size([12])


In [59]:
print(x.view(3,4))
print(y.view(3,4))
print(y.view(2,3,2))
print(y.view(2,2,3))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])


In [60]:
# squeeze : 텐서에서 차원이 1인 차원을 제거
y=y.view(3,1,4)
print(y.squeeze())
print(y.squeeze().size())
print(y.squeeze(0)) # 차원이 1인 차원을 (x)
print(y.squeeze(0).size()) 
print(y.squeeze(1)) # 차원이 1인 차원을 제거(0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
torch.Size([3, 4])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
torch.Size([3, 1, 4])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [61]:
x=torch.FloatTensor([[1,2],[3,4]])
print(x)
print(x.size()) # -> [2,2] 기본인 상태
print(x.unsqueeze(2)) # -> [2,2,1] 로 만들어지게된다
print(x.unsqueeze(1)) # -> [2,1,2] 로 만들어지게된다
print(x.unsqueeze(-1)) # -> [2,2,1] 로 만들어지게된다
print(x.reshape(2,2,1)) # -> [2,2,1]

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1., 2.]],

        [[3., 4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])


In [62]:
x=y.view(3,2,-1)
print(x)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [63]:
x=torch.FloatTensor([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [64]:
x=torch.randperm(40)
x=x.view(10,-1)
print(x)
print(x.size())
split=x.split(4, dim=0) # 자르기 할 데이터의 크기
for s in split:
    print(s.size())


tensor([[33, 15, 24, 39],
        [35, 26, 20, 23],
        [ 6, 25, 28,  5],
        [ 2, 12, 37,  9],
        [22, 32, 16, 34],
        [ 4, 13, 11, 18],
        [ 3,  8, 38, 14],
        [27, 17, 29,  7],
        [36, 10, 21,  1],
        [ 0, 19, 31, 30]])
torch.Size([10, 4])
torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [65]:
chunks=x.chunk(2, dim=0) #블록의 갯수
print(chunks)
for c in chunks:
    print(c.size())

(tensor([[33, 15, 24, 39],
        [35, 26, 20, 23],
        [ 6, 25, 28,  5],
        [ 2, 12, 37,  9],
        [22, 32, 16, 34]]), tensor([[ 4, 13, 11, 18],
        [ 3,  8, 38, 14],
        [27, 17, 29,  7],
        [36, 10, 21,  1],
        [ 0, 19, 31, 30]]))
torch.Size([5, 4])
torch.Size([5, 4])


In [66]:
x=torch.FloatTensor([[[1,1],[2,2]],[[3,3],[4,4]],[[5,5],[6,6]]])
print(x)
print(x.size())

tensor([[[1., 1.],
         [2., 2.]],

        [[3., 3.],
         [4., 4.]],

        [[5., 5.],
         [6., 6.]]])
torch.Size([3, 2, 2])


In [67]:
indice=torch.LongTensor([2,1])

y=x.index_select(dim=0, index=indice)
print(y)

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])


In [68]:
x=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
y=torch.FloatTensor([[11,12,13],[14,15,16],[17,18,19]])

print(x.size(), y.size())


torch.Size([3, 3]) torch.Size([3, 3])


In [69]:
z =torch.cat([x, y], dim=0)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [11., 12., 13.],
        [14., 15., 16.],
        [17., 18., 19.]])
torch.Size([6, 3])


In [70]:
z = torch.cat([x, y], dim=
1)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 11., 12., 13.],
        [ 4.,  5.,  6., 14., 15., 16.],
        [ 7.,  8.,  9., 17., 18., 19.]])
torch.Size([3, 6])


In [71]:
x=torch.FloatTensor([[1,2,3],[4,5,6],[7,8,9]])
y=torch.FloatTensor([[11,12,13],[14,15,16],[17,18,19]])

In [72]:
# expand() 차원이 1인 것을 크기 늘려 줌
a=np.arange(1, 13)
x=torch.from_numpy(a).view(3,1,4)
y=x.expand(3,2,4)
print(y)

tensor([[[ 1,  2,  3,  4],
         [ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [ 9, 10, 11, 12]]], dtype=torch.int32)


In [73]:
y2=torch.cat([x]*3, dim=1) #[0,1,2]
y2

tensor([[[ 1,  2,  3,  4],
         [ 1,  2,  3,  4],
         [ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8],
         [ 5,  6,  7,  8],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [ 9, 10, 11, 12],
         [ 9, 10, 11, 12]]], dtype=torch.int32)

In [74]:
x=torch.randperm(10) #0 ~ n-1 까지
x2=torch.randperm(2*5) #0 ~ n-1 까지
x3=torch.randperm(2**5) #0 ~ n-1 까지
print(x)
print(x2)
print(x3)

tensor([0, 8, 7, 2, 4, 5, 1, 9, 3, 6])
tensor([1, 4, 8, 2, 6, 9, 7, 3, 0, 5])
tensor([ 9, 23, 11, 29, 31,  4, 14, 22, 13, 21, 28, 10,  8, 26,  7, 19,  0, 16,
         6, 27, 25,  5, 24, 15,  2, 20,  1, 18, 17, 12,  3, 30])


In [75]:
x=torch.randperm(27).view(3,3,-1)
print(x)

tensor([[[ 9, 23, 17],
         [ 5, 26,  6],
         [20, 15,  8]],

        [[ 2,  0, 22],
         [ 3, 13, 11],
         [ 1, 10, 24]],

        [[ 7, 16,  4],
         [12, 18, 21],
         [14, 25, 19]]])


In [76]:
y=x.argmax(dim=0)
y1=x.argmax(dim=1)
print(y)
print(y1)

tensor([[0, 0, 1],
        [2, 0, 2],
        [0, 2, 1]])
tensor([[2, 1, 0],
        [1, 1, 2],
        [2, 2, 1]])


In [77]:
values,indices=torch.topk(x,k=1, dim=-1)
print(values)
print(values.size())
print(indices)
print(indices.size())

tensor([[[23],
         [26],
         [20]],

        [[22],
         [13],
         [24]],

        [[16],
         [21],
         [25]]])
torch.Size([3, 3, 1])
tensor([[[1],
         [1],
         [0]],

        [[2],
         [1],
         [2]],

        [[1],
         [2],
         [1]]])
torch.Size([3, 3, 1])


In [78]:
values,indices=torch.topk(x,k=2, dim=-1)
print(values)
print(values.size())
print(indices)
print(indices.size())

tensor([[[23, 17],
         [26,  6],
         [20, 15]],

        [[22,  2],
         [13, 11],
         [24, 10]],

        [[16,  7],
         [21, 18],
         [25, 19]]])
torch.Size([3, 3, 2])
tensor([[[1, 2],
         [1, 2],
         [0, 1]],

        [[2, 0],
         [1, 2],
         [2, 1]],

        [[1, 0],
         [2, 1],
         [1, 2]]])
torch.Size([3, 3, 2])


In [79]:
x=torch.FloatTensor([i+1 for i in range(3**2)]).view(3,-1)
print(x)
mask=x>4
print(mask)
y=x.masked_fill(mask, value=100)
print(y)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[False, False, False],
        [False,  True,  True],
        [ True,  True,  True]])
tensor([[  1.,   2.,   3.],
        [  4., 100., 100.],
        [100., 100., 100.]])


In [80]:
print(torch.ones(2,3))
print(torch.zeros(2,3))

print(torch.ones_like(x)) # x 크기만큼 1을 넣겠다
print(torch.zeros_like(x)) # x 크기만큼 0을 넣겠다

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
