In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


torch.manual_seed(1) 

In [2]:
x1_train= torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train= torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train= torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train= torch.FloatTensor([[152], [185], [180], [196], [142]])

In [3]:
# 가중치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [4]:
optimizer=optim.SGD([w1, w2, w3, b], lr=1e-5)
nb_epochs=100000

for epcho in range(nb_epochs):
    hypothesis=x1_train*w1 + x2_train*w2 + x3_train*w3 + b

    cost=torch.mean((hypothesis - y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epcho%400==0:
        print('Epoch=', epcho, 'w1=', w1.item(), 'w2=', w2.item(), 'w3=', w3.item(), 'b=', b.item(), 'cost=', cost.item())

Epoch= 0 w1= 0.29401201009750366 w2= 0.2935999929904938 w3= 0.2973800003528595 b= 0.0034199999645352364 cost= 29661.80078125
Epoch= 400 w1= 0.6894262433052063 w2= 0.6434438228607178 w3= 0.6777952909469604 b= 0.00836699828505516 cost= 1.375730276107788
Epoch= 800 w1= 0.7088890075683594 w2= 0.622265636920929 w3= 0.6794635057449341 b= 0.008947668597102165 cost= 1.1678179502487183
Epoch= 1200 w1= 0.7265268564224243 w2= 0.6033490300178528 w3= 0.6807023882865906 b= 0.009511923417448997 cost= 0.999893844127655
Epoch= 1600 w1= 0.7425243258476257 w2= 0.5864613652229309 w3= 0.6815593838691711 b= 0.010061148554086685 cost= 0.8641611337661743
Epoch= 2000 w1= 0.7570484280586243 w2= 0.5713934898376465 w3= 0.6820759177207947 b= 0.01059654913842678 cost= 0.7543893456459045
Epoch= 2400 w1= 0.7702491283416748 w2= 0.5579580664634705 w3= 0.6822887063026428 b= 0.011119304224848747 cost= 0.6654970645904541
Epoch= 2800 w1= 0.7822605967521667 w2= 0.5459862947463989 w3= 0.6822317242622375 b= 0.0116303777322173

In [14]:
x_train = torch.FloatTensor([[73, 80, 75],
[93, 88, 93],
[89, 91, 80],
[96, 98, 100],
[73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [15]:
W=torch.zeros((3,1), requires_grad=True)
b=torch.zeros(1, requires_grad=True)

optimizer=optim.SGD([W,b], lr=1e-5)

nb_epochs=2000

for epcho in range(nb_epochs):
    hypothesis=x_train.matmul(W)+b

    cost=torch.mean((hypothesis - y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epcho%100==0:
        print('Epoch=', epcho, 'hypothesis=', hypothesis.squeeze().detach(), 'cost=', cost.item())

Epoch= 0 hypothesis= tensor([0., 0., 0., 0., 0.]) cost= 29661.80078125
Epoch= 100 hypothesis= tensor([154.0433, 185.0925, 175.8312, 198.5701, 141.2221]) cost= 5.754572868347168
Epoch= 200 hypothesis= tensor([154.0278, 185.0649, 175.9335, 198.5128, 141.2284]) cost= 5.512386322021484
Epoch= 300 hypothesis= tensor([154.0120, 185.0385, 176.0329, 198.4569, 141.2353]) cost= 5.281667232513428
Epoch= 400 hypothesis= tensor([153.9960, 185.0133, 176.1295, 198.4022, 141.2426]) cost= 5.061906814575195
Epoch= 500 hypothesis= tensor([153.9797, 184.9892, 176.2233, 198.3488, 141.2504]) cost= 4.852423667907715
Epoch= 600 hypothesis= tensor([153.9632, 184.9662, 176.3143, 198.2966, 141.2586]) cost= 4.652731418609619
Epoch= 700 hypothesis= tensor([153.9465, 184.9442, 176.4029, 198.2456, 141.2672]) cost= 4.4622650146484375
Epoch= 800 hypothesis= tensor([153.9296, 184.9232, 176.4888, 198.1958, 141.2762]) cost= 4.280604362487793
Epoch= 900 hypothesis= tensor([153.9126, 184.9032, 176.5724, 198.1471, 141.2855]

#nn.Modual 사용_single_regression

In [16]:
torch.manual_seed(1)
# 데이터
x_train= torch.FloatTensor([[1], [2], [3]])
y_train= torch.FloatTensor([[2], [4], [6]])

In [18]:
model=nn.Linear(1,1)
print(list(model.parameters()))

optimizer=torch.optim.SGD(model.parameters(), lr=0.01)

[Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


In [19]:
nb_epochs=2000

for epcho in range(nb_epochs):
    prediction=model(x_train)

    cost=F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epcho%100==0:
        print('epcho=', epcho, 'cost=', cost.item())

epcho= 0 cost= 18.562185287475586
epcho= 100 cost= 0.12805092334747314
epcho= 200 cost= 0.07912760227918625
epcho= 300 cost= 0.048896174877882004
epcho= 400 cost= 0.030214829370379448
epcho= 500 cost= 0.01867094449698925
epcho= 600 cost= 0.011537504382431507
epcho= 700 cost= 0.007129476871341467
epcho= 800 cost= 0.004405592102557421
epcho= 900 cost= 0.002722370671108365
epcho= 1000 cost= 0.0016822535544633865
epcho= 1100 cost= 0.0010395277058705688
epcho= 1200 cost= 0.0006423679296858609
epcho= 1300 cost= 0.00039694414590485394
epcho= 1400 cost= 0.0002452871121931821
epcho= 1500 cost= 0.0001515713956905529
epcho= 1600 cost= 9.366295853396878e-05
epcho= 1700 cost= 5.7875975471688434e-05
epcho= 1800 cost= 3.576429298846051e-05
epcho= 1900 cost= 2.2100233763922006e-05


In [20]:
new_data=torch.FloatTensor([[4.0]])

pred_y=model(new_data)
print("예측값:", pred_y)

예측값: tensor([[7.9926]], grad_fn=<AddmmBackward0>)


# nn.Modual 사용 Mul_regression 구현

In [21]:
x_train = torch.FloatTensor([[73, 80, 75],
[93, 88, 93],
[89, 91, 80],
[96, 98, 100],
[73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [22]:
model=nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.5435,  0.3462, -0.1188]], requires_grad=True), Parameter containing:
tensor([0.2937], requires_grad=True)]


In [23]:
optimizer=torch.optim.SGD(model.parameters(), lr=1e-5)
nb_epochs=100000

for epcho in range(nb_epochs):
    prediction=model(x_train)
    cost=F.mse_loss(prediction, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epcho%400==0:
        print('epcho=', epcho, 'cost=', cost.item())

epcho= 0 cost= 39535.2265625
epcho= 400 cost= 11.874940872192383
epcho= 800 cost= 10.212570190429688
epcho= 1200 cost= 8.791491508483887
epcho= 1600 cost= 7.575187683105469
epcho= 2000 cost= 6.533003330230713
epcho= 2400 cost= 5.639214038848877
epcho= 2800 cost= 4.872000694274902
epcho= 3200 cost= 4.213054180145264
epcho= 3600 cost= 3.6467061042785645
epcho= 4000 cost= 3.159735918045044
epcho= 4400 cost= 2.7407870292663574
epcho= 4800 cost= 2.380223274230957
epcho= 5200 cost= 2.0698187351226807
epcho= 5600 cost= 1.8025128841400146
epcho= 6000 cost= 1.5722583532333374
epcho= 6400 cost= 1.3739006519317627
epcho= 6800 cost= 1.202953815460205
epcho= 7200 cost= 1.0556285381317139
epcho= 7600 cost= 0.9286408424377441
epcho= 8000 cost= 0.8191632032394409
epcho= 8400 cost= 0.724780261516571
epcho= 8800 cost= 0.6434122323989868
epcho= 9200 cost= 0.5732322335243225
epcho= 9600 cost= 0.5127170085906982
epcho= 10000 cost= 0.460521399974823
epcho= 10400 cost= 0.41549739241600037
epcho= 10800 cost= 

In [24]:
new_data=torch.FloatTensor([[73,80,75]])
pred_y=model(new_data)
print('예측값:', pred_y)

예측값: tensor([[152.3810]], grad_fn=<AddmmBackward0>)


# 단순선형회귀 클래스로 구현

In [25]:
torch.manual_seed(1)
# 데이터
x_train= torch.FloatTensor([[1], [2], [3]])
y_train= torch.FloatTensor([[2], [4], [6]])

In [26]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(1,1)

    def forward(self, x):
        return self.linear(x)

In [27]:
model=LinearRegressionModel()
optimizer=torch.optim.SGD(model.parameters(), lr=0.01)

nb_epochs=2000
for epcho in range(nb_epochs):
    prediction=model(x_train)

    cost=F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epcho%100==0:
        print('epcho=', epcho, 'cost=', cost.item())

epcho= 0 cost= 13.103541374206543
epcho= 100 cost= 0.00279058120213449
epcho= 200 cost= 0.00172441138420254
epcho= 300 cost= 0.0010655784280970693
epcho= 400 cost= 0.0006584661896340549
epcho= 500 cost= 0.0004068926500622183
epcho= 600 cost= 0.0002514346851967275
epcho= 700 cost= 0.00015537298168055713
epcho= 800 cost= 9.601024794392288e-05
epcho= 900 cost= 5.9327696362743154e-05
epcho= 1000 cost= 3.66610438504722e-05
epcho= 1100 cost= 2.2655576685792767e-05
epcho= 1200 cost= 1.3999051589053124e-05
epcho= 1300 cost= 8.65114816406276e-06
epcho= 1400 cost= 5.346103989722906e-06
epcho= 1500 cost= 3.3032331430149497e-06
epcho= 1600 cost= 2.04174443751981e-06
epcho= 1700 cost= 1.2618406799447257e-06
epcho= 1800 cost= 7.801028800713539e-07
epcho= 1900 cost= 4.823282324650791e-07


In [28]:
x_train = torch.FloatTensor([[73, 80, 75],
[93, 88, 93],
[89, 91, 80],
[96, 98, 100],
[73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [31]:
class MulLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)

    def forward(self, x):
        return self.linear(x)    

In [33]:
model=MulLinearRegressionModel()
optimizer=torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs=100000

for epcho in range(nb_epochs):
    prediction=model(x_train)

    cost=F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epcho%500==0:
        print('epcho=', epcho, 'cost=', cost.item())

epcho= 0 cost= 19207.734375
epcho= 500 cost= 5.815417289733887
epcho= 1000 cost= 4.5832719802856445
epcho= 1500 cost= 3.643120527267456
epcho= 2000 cost= 2.919158458709717
epcho= 2500 cost= 2.3568572998046875
epcho= 3000 cost= 1.9164378643035889
epcho= 3500 cost= 1.5688223838806152
epcho= 4000 cost= 1.292563796043396
epcho= 4500 cost= 1.0715982913970947
epcho= 5000 cost= 0.8938740491867065
epcho= 5500 cost= 0.7502154111862183
epcho= 6000 cost= 0.6335490345954895
epcho= 6500 cost= 0.5384930372238159
epcho= 7000 cost= 0.46077290177345276
epcho= 7500 cost= 0.3970680236816406
epcho= 8000 cost= 0.34470778703689575
epcho= 8500 cost= 0.3016139566898346
epcho= 9000 cost= 0.26604127883911133
epcho= 9500 cost= 0.2366916686296463
epcho= 10000 cost= 0.21240778267383575
epcho= 10500 cost= 0.19231131672859192
epcho= 11000 cost= 0.17566953599452972
epcho= 11500 cost= 0.16186730563640594
epcho= 12000 cost= 0.15042228996753693
epcho= 12500 cost= 0.14092476665973663
epcho= 13000 cost= 0.1330364793539047