In [21]:
import numpy as np

In [22]:
x_data1 = [[[73., 80., 75.],
            [93., 88., 93.],
            [89., 91., 80.],
            [96., 98., 100.],
            [73., 66., 70.]]]

t_data1 = [[152.],
           [185.],
           [180.],
           [196.],
           [142.]]

In [23]:
x_data=np.array(x_data1)
t_data=np.array(t_data1)
print(x_data)
print(t_data)

[[[ 73.  80.  75.]
  [ 93.  88.  93.]
  [ 89.  91.  80.]
  [ 96.  98. 100.]
  [ 73.  66.  70.]]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [24]:
w=np.random.rand(3,1) #3행 1열짜리
b=np.random.rand(1)
print(w,b)

[[0.06166625]
 [0.73220219]
 [0.85032475]] [0.17288522]


In [25]:
#손실 함수 만들기
def loss_func(x, t):
    y=np.dot(x, w)+b # y=XW+b
    return (np.sum((t-y)**2))/len(x) #MSE(에러의 평균을 제곱한것의 합)

In [26]:
def mul_numerical_derivative(f, x):
    delta_x=1e-4
    grad=np.zeros_like(x) # 미분결과 값 저장 배열

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx=it.multi_index

        tmp_val=x[idx]
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x)
        x[idx]=tmp_val-delta_x
        fx2=f(x)
        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()
    return grad 

In [27]:
def predict(x):
    y=np.dot(x,w)+b
    return y

In [28]:
learning_rate=1e-6

f=lambda x:loss_func(x_data, t_data)
print("Initial error value=", loss_func(x_data, t_data), 'w=',w, 'b=',b)

for step in range(100000):
    w-=learning_rate*mul_numerical_derivative(f, w)
    b-=learning_rate*mul_numerical_derivative(f, b)
    if step%400==0:
        print("step", step, "error value", loss_func(x_data, t_data), "w=", w, 'b=',b)

Initial error value= 5430.025709826148 w= [[0.06166625]
 [0.73220219]
 [0.85032475]] b= [0.17288522]
step 0 error value 3366.4891168174663 w= [[0.08965613]
 [0.76006446]
 [0.87778833]] b= [0.17314062]
step 400 error value 80.09943092398142 w= [[0.22690741]
 [0.85976286]
 [0.94185536]] b= [0.17450678]
step 800 error value 74.13528309081784 w= [[0.26198425]
 [0.85820997]
 [0.90790767]] b= [0.1749304]
step 1200 error value 68.63853028064472 w= [[0.29586549]
 [0.85627631]
 [0.87555575]] b= [0.17533231]
step 1600 error value 63.56989894238087 w= [[0.32858894]
 [0.85400751]
 [0.84471517]] b= [0.17571334]
step 2000 error value 58.89375277714739 w= [[0.36019142]
 [0.85144524]
 [0.81530649]] b= [0.1760743]
step 2400 error value 54.57771577319388 w= [[0.39070882]
 [0.8486275 ]
 [0.78725497]] b= [0.17641598]
step 2800 error value 50.59233863718191 w= [[0.42017604]
 [0.84558893]
 [0.76049021]] b= [0.17673911]
step 3200 error value 46.91080320875576 w= [[0.44862706]
 [0.84236105]
 [0.73494593]] b= 