In [2]:
import numpy as np

list1=[1, 3.5, '홍길동']

a=[1,2,3,4,5]
arr2=np.array(list1)
arr=np.array(a)

print(arr)
print(arr2)
print(list1)

[1 2 3 4 5]
['1' '3.5' '홍길동']
[1, 3.5, '홍길동']


In [3]:
arr3=np.array([1,2,3,])
print(arr3)
print(type(arr3))
print(arr3.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [6]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)
print(b)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
a1=[1,2,3,4,5,6,7,8,9]
arr1=np.array(a1).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# print(a+1)
print(a*2)
print(b+1)
print(b-1)
print(b*2)
print(b/2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


In [13]:
c=[[10,20,30]]
print(a+c)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 20, 30]]


In [17]:
d=np.array([10,20,30])
print(b+d)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [27]:
print(b.sum())
print(b)
print(b.sum(axis=0))
print(np.sum(b,axis=0))
print(b.sum(axis=1))
print(b.mean(axis=0))
print(b.mean(axis=1))
print(b.max(axis=0))
print(b.max(axis=1))


45
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[12 15 18]
[ 6 15 24]
[4. 5. 6.]
[2. 5. 8.]
[7 8 9]
[3 6 9]


In [36]:
print(a)
print(b)
print(b[:,2])
print(a[1][2])


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9]
6


In [43]:
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([10,20,30,40]).reshape(2,2)
print(a*b)
print(a.dot(b))

[[ 10  40]
 [ 90 160]]
[[ 70 100]
 [150 220]]


In [48]:
print(np.sqrt(b))
print(np.log(b))
print(b>25)

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]
[[2.30258509 2.99573227]
 [3.40119738 3.68887945]]
[[False False]
 [ True  True]]
